### ISSUE TITLE
StreamMediaServerKeeper引用ini-parser问题

### ISSUE THREAD

**Issue by funthing** [chatop2020/StreamNode-GB28181#10]
VS打开提示ini-parser依赖项有问题，不过程序可以正常运行，猜测这个ini-parser应该是.Net Framework的依赖项，.NetCore版本的应该是ini-parser-netstandard，切换成ini-parser-netstandard运行未发现问题，ini文件可以正常解析。

**Comment by chatop2020** [comment]
感谢提出，已经修正
