### ISSUE TITLE
GIT时错误

### ISSUE THREAD

**Issue by XtosX** [chatop2020/StreamNode-GB28181#12]
git clone https://github.com/chatop2020/StreamNode-GB28181.git
Cloning into 'StreamNode-GB28181'...
remote: Enumerating objects: 211, done.
remote: Counting objects: 100% (211/211), done.
remote: Compressing objects: 100% (140/140), done.
error: RPC failed; curl 56 OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 110
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
[root@localhost ~]# git config http.sslVerify "false"
fatal: not in a git directory
[root@localhost ~]# git config --global   http.sslVerify "false"
[root@localhost ~]# git config http.sslVerify "false"
fatal: not in a git directory

**Comment by chatop2020** [comment]
<img width="768" alt="QQ20201116-115451@2x" src="https://user-images.githubusercontent.com/64897311/99211170-b49a7880-2802-11eb-89b8-009a8bae707b.png">
我测过了，正常的，注意翻墙
