### ISSUE TITLE
readme是否可以增加编译运行的说明

### ISSUE THREAD

**Issue by ganttee** [chatop2020/StreamNode-GB28181#15]
没有接触过C# .net，折腾了一下午，还是没有跑起来。。。

是否可以把 编译 运行命令说明一下，帮助第一次接触项目的人，可以先跑起来，再去深究代码逻辑

感谢开源

**Comment by chatop2020** [comment]
在项目目录中运行
dotnet build 
//编译项目
编译出来以后在bin目录下的子目录里会生成很多dll文件，这里是可执行文件的地方，把readme里的配置文件放好配置好
dotnet 项目名称.dll 
//运行某个子目录

我最近在跨平台适配，做完后会对各平台做一下编译运行说明

**Comment by chatop2020** [comment]
等空一些的时候，建设一下wiki栏目
