### ISSUE TITLE
请问Centos7上面怎么编译? 谢谢!

### ISSUE THREAD

**Issue by addriumruss** [chatop2020/StreamNode-GB28181#16]

**Comment by funthing** [comment]
可以参考https://github.com/chatop2020/StreamNode-GB28181/issues/15

**Comment by addriumruss** [comment]
@funthing  你好 感谢回应！ 
可是还是没看懂啊：

在项目目录中运行
dotnet build
//编译项目
编译出来以后在bin目录下的子目录里会生成很多dll文件，这里是可执行文件的地方，把readme里的配置文件放好配置好
dotnet 项目名称.dll
//运行某个子目录

**Comment by chatop2020** [comment]
等空的时候，建设wiki栏目
