### ISSUE TITLE
keeper 里面config.ini IP的地址配置问题

### ISSUE THREAD

**Issue by YukiYlf** [chatop2020/StreamNode-GB28181#5]
IP地址配置--是OK的
如果换成域名---不行，无法返回列表

**Comment by YukiYlf** [comment]
不过可以多定义一个域名返回模式的字段也可以，这样不影响

**Comment by chatop2020** [comment]
keeper 的config.conf文件中的ipaddress是指keeper本机的ip地址，也意味着这个ip地址就是流媒体的ip地址
在streamnode向gb28181设备请求推流的时候，会将这个ipaddress的值写到sdp中，提交给摄像头。理论上只要摄像头支持域名dns解析那应该是能成功推流的，如果不支持或者没有正确配置摄像头的dns服务器，那就肯定会推流失败。
