### ISSUE TITLE
keeper 改变之后重新启动

### ISSUE THREAD

**Issue by YukiYlf** [chatop2020/StreamNode-GB28181#6]
如果keeper的配置config.conf改变之后，如果重新启动之后

对应的webapi----无法自动重来上来，验证很多次都是一样的情况

虽然不影响，只是问题放这里说明一下

**Comment by chatop2020** [comment]
这个我找找原因

**Comment by chatop2020** [comment]
已经改用新的process管理模块，这个情况我这边没有测出来了，如果有问题再说，先关了。
