### ISSUE TITLE
4G网络环境下streamid的那个流编码会变

### ISSUE THREAD

**Issue by YukiYlf** [chatop2020/StreamNode-GB28181#8]
如果是4G网络环境
1：我重启keeper --或者重启服务器ZLM
然后那个streamid就变化了  因为是动态的IP地址那个情况，好像

**Comment by YukiYlf** [comment]
string streamid =dev.IpAddress+ dev.DeviceId + camera.Camera.DeviceID ;

                // 修改，因为移动的IP会改变
                streamid =  dev.DeviceId + camera.Camera.DeviceID;


我测试一下看看，是否正确，，如果OK--
我回复这这里，，放弃了IP地址的

**Comment by chatop2020** [comment]
这块已经修复
