### ISSUE TITLE
StreamMediaServerKeeper适配Windows问题

### ISSUE THREAD

**Issue by funthing** [chatop2020/StreamNode-GB28181#9]
菜鸟有一个小小的疑问，StreamMediaServerKeeper这个项目是没有适配Windows吗？启动MediaServer的相关代码我看适配的是Linux和OSX。
另外就是直接使用process.StartInfo.FileName = "MediaServer路径"这样的形势启动MediaServer和process调用命令去启动MediaServer的相比较会有什么问题吗？感觉前者更容易实现跨平台。调用命令的话还要针对Linux和Windows编写不同的命令。是因为nohup的原因吗？

**Comment by YukiYlf** [comment]
windows  没测试，不过我现在环境是ubuntu
StreamMediaServerKeeper  --要和ZLM同一台服务器。感觉Windows很麻烦

**Comment by funthing** [comment]
> windows 没测试，不过我现在环境是ubuntu
> StreamMediaServerKeeper --要和ZLM同一台服务器。感觉Windows很麻烦

针对开发来说，确实windows不怎么受待见，zlm新手编译最不推荐平台：windows。

**Comment by chatop2020** [comment]
确实只适配了linux操作系统，因为我本身用macos前期在mac上做的测试，后来都在linux上做测试了，所以连mac的适配可能都存在问题，windows更加是没有去适配了。
近期我又比较忙，等空一些，我会把windows也适配起来的。

**Comment by chatop2020** [comment]
通过process启动是可行的，可能是因为我习惯linux了，所以一下子没有想到可以通过process来启动程序。
不过，适配其他操作系统还有较多的功能要改，主要是在进程开关和性能参数获取，这段时间太忙，暂时还没时间去搞，如果等不及，可以自己先改起来，可以的话给我提个pr

**Comment by funthing** [comment]
> 通过process启动是可行的，可能是因为我习惯linux了，所以一下子没有想到可以通过process来启动程序。
> 不过，适配其他操作系统还有较多的功能要改，主要是在进程开关和性能参数获取，这段时间太忙，暂时还没时间去搞，如果等不及，可以自己先改起来，可以的话给我提个pr

好的，我这边再测试下，

**Comment by chatop2020** [comment]
我开始适配windows操作系统

**Comment by funthing** [comment]
平时都是内网开发，刚看着教程pr了，但是看之前老哥提的pr说process不支持Linux和MacOS，迷茫中。

**Comment by funthing** [comment]
> 我开始适配windows操作系统

平时都是内网开发，刚看着教程pr了，但是看之前老哥提的pr说process不支持Linux和MacOS，迷茫中。

**Comment by chatop2020** [comment]
我最近一直在出差，回去后看看pr

**Comment by chatop2020** [comment]
已经合并，跨平台这块，还有一些要更新，目前这个可以做为临时解决方案。
